version: "3"
services:
    nginx:
        # image: nginx:stable-apine
        ports: 
            - "80:80"
    node-app:
        deploy:
            replicas: 8 # Set how many instances of a specific service you want to run, in this case 8 containers
            restart_policy:
                condition: any
            update_config:
                parallelism: 2 #Update two containers at a time
                delay: 15s
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - SESSION_SECRET=${SESSION_SECRET}
        command: node app.js
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}