version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "5000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        # ports:
        #     - "5000:5000"
        environment:
            - PORT=5000
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=karokojnr
            - MONGO_INITDB_ROOT_PASSWORD=karokojnr
        volumes: 
            - ./data:/data/db # named volume (<name>: path )
    redis:
        image: redis
# volumes: # list of named volumes
#     mongo-db:
