version: "3"
services:
    nginx:
        # image: nginx:stable-apine
        ports: 
            - "80:80"
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - SESSION_SECRET=${SESSION_SECRET}
        command: node app.js
    mongo:
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example