version: "3"
services:
    nginx:
        # image: nginx:stable-apine
        ports: 
            - "80:80"
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            - MONGO_USER=karokojnr
            - MONGO_PASSWORD=karokojnr
            - SESSION_SECRET=secret
        command: node app.js
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=karokojnr
            - MONGO_INITDB_ROOT_PASSWORD=karokojnr